export const JEWELRY_CONSTITUTION = {
  role: "Jewelry image prompt specialist for luxury product photography",
  priorities: [
    "Photorealistic metal and gemstone rendering",
    "Professional studio lighting and composition",
    "Accurate material representation (gold, silver, rose gold)",
    "Clean, centered product focus",
  ],
  nonNegotiables: [
    "No distortion or perspective warping",
    "No blur or low-resolution output",
    "No unrealistic or cartoon-style rendering",
    "No cluttered or distracting backgrounds",
  ],
  /** Referans kalite: Medusa madalyon seviyesi – yüksek kontrast metal, high-relief, fotogerçekçi makro */
  defaultQualityConstraints: [
    "masterpiece",
    "ultra high detail",
    "8k resolution",
    "macro jewelry photography",
    "100mm macro lens",
    "extreme close-up",
    "sharp focus on intricate textures",
    "high-contrast studio lighting",
    "photorealistic metal reflections",
    "caustic light patterns",
    "deep shadows for depth",
    "extreme surface detail",
    "high-relief sculptural depth",
    "luxury product photography",
    "cinematic composition",
  ],
  defaultNegativeConstraints: [
    "plastic look",
    "flat metal texture",
    "blurry edges",
    "fuzzy or washed silhouette",
    "low quality",
    "cartoonish",
    "dull reflections",
    "optical blur on the jewelry",
    "low resolution",
    "cheap jewelry look",
    "warped ring shape",
    "text",
    "watermark",
    "logo",
    "distorted",
    "cluttered",
    "amateur",
  ],
  /** Görsel API için kalite ifadesi – Medusa referans seviyesi */
  imageQualitySuffix:
    "shot with 100mm macro lens, extreme close-up, sharp focus on intricate textures, high-contrast studio lighting, photorealistic metal reflections, caustic light patterns, deep shadows for depth, 8k resolution, cinematic composition",

  /** 3D Export (Meshy) modu – Image to 3D için optimize edilmiş kurallar. Meshy yoğun detayda geometri ayırt edemez – net katman ayrımı gerekli. */
  mode3DExport: {
    qualityConstraints: [
      "plain white or light gray background #F5F5F5",
      "directional studio lighting with hard silhouette edges",
      "crisp micro-contrast between relief planes",
      "short defined shadows that carve form, not muddy ambient",
      "product centered with 15% margin padding",
      "8k resolution",
      "tack sharp focus edge to edge on the jewelry",
      "clear geometric separation between elements",
      "distinct relief layers with readable depth",
      "crisp sharp edges, no fuzzy transitions",
      "moderate detail density – avoid overly busy composition",
      "structured composition for 3D conversion",
      "each element has clear silhouette boundary",
      "high contrast between relief levels",
      "single clear three-quarter isometric ~45° (Remaura View A), not flat front-only",
      "matte metal, sharp line definition",
    ],
    negativeConstraints: [
      "black background",
      "reflective surface",
      "gradient background",
      "cluttered",
      "indistinct edges",
      "blurry engraving",
      "washed gradients that lose relief detail",
      "muddy lines",
      "merged details",
      "overly busy composition",
      "extreme detail density",
      "washed-out or fuzzy silhouette",
      "ambient-only flat lighting with no edge definition",
    ],
    imageQualitySuffix:
      "plain white background, directional studio lighting with crisp silhouette edges, clear geometric separation between elements, distinct relief layers, moderate detail density, structured composition for Meshy 3D conversion",
  },
} as const;
