export const JEWELRY_CONSTITUTION = {
  role: "Jewelry image prompt specialist for luxury product photography",
  priorities: [
    "Photorealistic metal and gemstone rendering",
    "Professional studio lighting and composition",
    "Accurate material representation (gold, silver, rose gold)",
    "Clean, centered product focus",
  ],
  nonNegotiables: [
    "No distortion or perspective warping",
    "No blur or low-resolution output",
    "No unrealistic or cartoon-style rendering",
    "No cluttered or distracting backgrounds",
  ],
  /** Referans kalite: Medusa madalyon seviyesi – yüksek kontrast metal, high-relief, fotogerçekçi makro */
  defaultQualityConstraints: [
    "masterpiece",
    "ultra high detail",
    "8k resolution",
    "macro jewelry photography",
    "100mm macro lens",
    "extreme close-up",
    "sharp focus on intricate textures",
    "high-contrast studio lighting",
    "photorealistic metal reflections",
    "caustic light patterns",
    "deep shadows for depth",
    "extreme surface detail",
    "high-relief sculptural depth",
    "luxury product photography",
    "cinematic composition",
  ],
  defaultNegativeConstraints: [
    "plastic look",
    "flat metal texture",
    "blurry edges",
    "low quality",
    "cartoonish",
    "dull reflections",
    "soft focus",
    "low resolution",
    "cheap jewelry look",
    "warped ring shape",
    "text",
    "watermark",
    "logo",
    "distorted",
    "cluttered",
    "amateur",
  ],
  /** Görsel API için kalite ifadesi – Medusa referans seviyesi */
  imageQualitySuffix:
    "shot with 100mm macro lens, extreme close-up, sharp focus on intricate textures, high-contrast studio lighting, photorealistic metal reflections, caustic light patterns, deep shadows for depth, 8k resolution, cinematic composition",

  /** 3D Export (Meshy) modu – Image to 3D için optimize edilmiş kurallar. Meshy yoğun detayda geometri ayırt edemez – net katman ayrımı gerekli. */
  mode3DExport: {
    qualityConstraints: [
      "plain white or light gray background #F5F5F5",
      "soft diffused studio lighting",
      "minimal shadows",
      "product centered with 15% margin padding",
      "8k resolution",
      "sharp focus",
      "clear geometric separation between elements",
      "distinct relief layers with readable depth",
      "crisp sharp edges",
      "moderate detail density – avoid overly busy composition",
      "structured composition for 3D conversion",
      "each element has clear silhouette boundary",
      "high contrast between relief levels",
      "single clear view front or 3/4 angle",
      "matte metal, sharp line definition",
    ],
    negativeConstraints: [
      "black background",
      "dramatic lighting",
      "chiaroscuro",
      "deep shadows",
      "reflective surface",
      "caustic light",
      "strong highlights",
      "gradient background",
      "cluttered",
      "soft edges",
      "blurry engraving",
      "smooth gradients that lose detail",
      "muddy lines",
      "merged details",
      "overly busy composition",
      "extreme detail density",
    ],
    imageQualitySuffix: "plain white background, soft diffused lighting, clear geometric separation between elements, distinct relief layers, moderate detail density, structured composition for Meshy 3D conversion",
  },
} as const;
